name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -project template/template.xcodeproj -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=$(xcrun simctl list devices available | grep -oE 'iPhone [^ ]+' | head -1)
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild build-for-testing -scheme "$scheme" -project template/template.xcodeproj -destination "platform=$platform,name=$device"

      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=$(xcrun simctl list devices available | grep -oE 'iPhone [^ ]+' | head -1)
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild test-without-building -scheme "$scheme" -project template/template.xcodeproj -destination "platform=$platform,name=$device"
